# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TTT_GameQkRLkW.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        font = QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 801, 81))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(32)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setKerning(True)
        self.label.setFont(font1)
        self.label.setTextFormat(Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(30, 100, 741, 431))
        font2 = QFont()
        font2.setBold(False)
        font2.setItalic(False)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferAntialias)
        self.frame.setFont(font2)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(u"background-color: rgb(208, 208, 208);")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.pushButton_10 = QPushButton(self.frame)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(250, 370, 241, 41))
        font3 = QFont()
        font3.setPointSize(15)
        font3.setBold(False)
        self.pushButton_10.setFont(font3)
        self.pushButton_10.setStyleSheet(u"background-color: rgb(177, 177, 177);")
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 10, 681, 61))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(20)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setKerning(True)
        self.label_3.setFont(font4)
        self.label_3.setTextFormat(Qt.PlainText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 310, 681, 61))
        font5 = QFont()
        font5.setFamilies([u"Arial"])
        font5.setPointSize(12)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setKerning(True)
        self.label_5.setFont(font5)
        self.label_5.setStyleSheet(u"color: rgb(211, 0, 4);")
        self.label_5.setTextFormat(Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(250, 70, 241, 241))
        font6 = QFont()
        font6.setStyleStrategy(QFont.PreferDefault)
        self.frame_2.setFont(font6)
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.pushButton_1 = QPushButton(self.frame_2)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(0, 0, 81, 81))
        font7 = QFont()
        font7.setKerning(True)
        font7.setStyleStrategy(QFont.PreferDefault)
        self.pushButton_1.setFont(font7)
        self.pushButton_1.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_1.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setAutoExclusive(False)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_3 = QPushButton(self.frame_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(160, 0, 81, 81))
        self.pushButton_3.setFont(font7)
        self.pushButton_3.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_3.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoExclusive(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_2 = QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(80, 0, 81, 81))
        font8 = QFont()
        font8.setBold(False)
        font8.setItalic(False)
        font8.setKerning(True)
        font8.setStyleStrategy(QFont.PreferDefault)
        self.pushButton_2.setFont(font8)
        self.pushButton_2.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_2.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_6 = QPushButton(self.frame_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(160, 80, 81, 81))
        self.pushButton_6.setFont(font7)
        self.pushButton_6.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_6.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoExclusive(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_4 = QPushButton(self.frame_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 80, 81, 81))
        self.pushButton_4.setFont(font7)
        self.pushButton_4.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_4.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_5 = QPushButton(self.frame_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(80, 80, 81, 81))
        self.pushButton_5.setFont(font8)
        self.pushButton_5.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_5.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_7 = QPushButton(self.frame_2)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(0, 160, 81, 81))
        self.pushButton_7.setFont(font7)
        self.pushButton_7.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_7.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setAutoExclusive(False)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_8 = QPushButton(self.frame_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(80, 160, 81, 81))
        self.pushButton_8.setFont(font8)
        self.pushButton_8.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_8.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setAutoExclusive(False)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_9 = QPushButton(self.frame_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(160, 160, 81, 81))
        self.pushButton_9.setFont(font7)
        self.pushButton_9.setFocusPolicy(Qt.StrongFocus)
        self.pushButton_9.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setAutoExclusive(False)
        self.pushButton_9.setAutoDefault(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton_1.setDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_9.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tic Tac Toe - LAN", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Tic Tac Toe", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Spiel beenden", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Statusmeldung", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Fehlermeldung: Error", None))
        self.pushButton_1.setText("")
        self.pushButton_3.setText("")
        self.pushButton_2.setText("")
        self.pushButton_6.setText("")
        self.pushButton_4.setText("")
        self.pushButton_5.setText("")
        self.pushButton_7.setText("")
        self.pushButton_8.setText("")
        self.pushButton_9.setText("")
    # retranslateUi

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.show()